version: "3.8"
services:
  nats-streaming:
    command:
      - "--cluster_id"
      - ${NATS_CLUSTER_ID}
    image: library/nats-streaming:latest
    restart: always
    container_name: nats-streaming
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - ./volumes/nats_data_store:/repository:Z

volumes:
  data: